language: node_js

dist: trusty

node_js:
  - 9.3.0

before_install:
  - node --version && yarn --version

install:
  - yarn install

script:
  - yarn run test

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules
